### ISSUE TITLE
(Fix) Usage description is outdated

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/e2e-test-token-wizard#11]
I've tried to use utility with usage description in `README` https://github.com/poanetwork/e2e-test-token-wizard#usage:
```
/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/pages/Page.js
/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/pages/WizardStep3.js
/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/tests/BaseTest.js
/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/pages/TierPage.js
/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/entity/Currency.js
/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/pages/CrowdsalePage.js
/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/pages/InvestPage.js
module.js:540
    throw err;
    ^

Error: Cannot find module './tests/Test2.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/index.js:5:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by dennis00010011b** [comment]
@vbaranov 
fixed
