### ISSUE TITLE
(Bug) stuck at step 2 with simple scenario

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/e2e-test-token-wizard#12]
create-poa-crowdsale@1.0.38

Scenario:
```
{ "account": "0xF16AB2EA0a7F7B28C267cbA3Ed211Ea5c6e27411",
  "privateKey": "03c06a9fab22fe0add145e337c5a8251e140f74468d72eab17ec7419ab812cd0",
  "networkID":4,

  "name": "T1RnWn_0005.json",
  "ticker": "test",
  "decimals": 3,
  "reservedTokens":[
  ],
  "walletAddress":"0xF16AB2EA0a7F7B28C267cbA3Ed211Ea5c6e27411",
  "gasprice": 40,
  "mincap": 1,
  "whitelisting":false,
  "tiers":[
    {
      "name":"###1",
      "allowModify": true,
      "startDate": "02/16/2018",
      "startTime": "03:15pm",
      "endDate":"02/16/2018",
      "endTime":"03:30pm",
      "rate":100,
      "supply": 200,
      "whitelist":[]
    }]
}
```
Log: [error_15_02.log](https://github.com/poanetwork/e2e-test-token-wizard/files/1727369/error_15_02.log)

![bug](https://user-images.githubusercontent.com/4341812/36254147-fe38e596-125a-11e8-82f6-b01d7a9d6506.gif)

**Comment by vbaranov** [comment]
I tried with `1.0.44` version. 
It stuck at the same page with the same error:
```
viktors-MacBook-Pro:Test viktor$ node index.js 
./node_modules/create-poa-crowdsale/MetaMask.crx
./node_modules/create-poa-crowdsale/MetaMask.crx
/Users/viktor/Documents/POANetwork/Test/node_modules/selenium-webdriver/lib/promise.js:2626
        throw error;
        ^

TimeoutError: Waiting for element to be located By(xpath, //*[@id="root"]/div/section/div[3]/a)
Wait timed out after 20000ms
    at /Users/viktor/Documents/POANetwork/Test/node_modules/selenium-webdriver/lib/promise.js:2201:17
    at ManagedPromise.invokeCallback_ (/Users/viktor/Documents/POANetwork/Test/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/Users/viktor/Documents/POANetwork/Test/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Users/viktor/Documents/POANetwork/Test/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/Users/viktor/Documents/POANetwork/Test/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /Users/viktor/Documents/POANetwork/Test/node_modules/selenium-webdriver/lib/promise.js:668:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: Waiting for element to be located By(xpath, //*[@id="root"]/div/section/div[3]/a)
    at scheduleWait (/Users/viktor/Documents/POANetwork/Test/node_modules/selenium-webdriver/lib/promise.js:2188:20)
    at ControlFlow.wait (/Users/viktor/Documents/POANetwork/Test/node_modules/selenium-webdriver/lib/promise.js:2517:12)
    at thenableWebDriverProxy.wait (/Users/viktor/Documents/POANetwork/Test/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
    at WizardStep2.clickWithWait (/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/pages/Page.js:50:34)
    at WizardStep2.clickButtonContinue (/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/pages/WizardStep2.js:38:11)
    at Test1.run (/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/tests/Test1.js:110:21)
    at createPOACrowdsale (/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/index.js:39:15)
    at Object.<anonymous> (/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/index.js:27:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
From: Task: WebElement.click()
    at thenableWebDriverProxy.schedule (/Users/viktor/Documents/POANetwork/Test/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at WebElementPromise.schedule_ (/Users/viktor/Documents/POANetwork/Test/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
    at WebElementPromise.click (/Users/viktor/Documents/POANetwork/Test/node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
    at WizardStep2.clickWithWait (/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/pages/Page.js:51:16)
    at WizardStep2.clickButtonContinue (/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/pages/WizardStep2.js:38:11)
    at Test1.run (/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/tests/Test1.js:110:21)
    at createPOACrowdsale (/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/index.js:39:15)
    at Object.<anonymous> (/Users/viktor/Documents/POANetwork/Test/node_modules/create-poa-crowdsale/index.js:27:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
```
